### ISSUE TITLE
Improve heuristic identification of transport reactions

### ISSUE THREAD

**Issue by stelmo** [LCSB-BioCore/FBCModelTests.jl#32]
Currently PTS style transporters are not recognized.

**Comment by exaexa** [comment]
Is there some example of that? (also some way to actually recognize them?)

**Comment by exaexa** [comment]
(also not sure if this is a bug (solution is known) or a wishlist (we need to invent one))

**Comment by stelmo** [comment]
In memote.py they have a more robust way of testing for transporters, see [here](https://github.com/opencobra/memote/blob/81a55a163262a0e06bfcb036d98e8e551edc3873/src/memote/suite/tests/test_basic.py#L406). We should make sure our transporter identification function is also robust

**Comment by stelmo** [comment]
Fixed in #70: no heuristics anymore, just SBO annotations
