### ISSUE TITLE
Add additional tests

### ISSUE THREAD

**Issue by stelmo** [LCSB-BioCore/FBCModelTests.jl#38]
- [x] metabolite connectivity
- [x] unbounded flux in default medium

**Comment by exaexa** [comment]
I think this is partially done and partially addressed by #50 ?

**Comment by exaexa** [comment]
(cc @Fl-Sch pls confirm if you can :] )

**Comment by vm-vh** [comment]
Yeah these functions were both included in #50 (see the last 2 functions in Consistency.jl)

**Comment by exaexa** [comment]
@vm-vh ok perfect, thanks for confirm :]
